version: '3'
services:
#---------MySQL------------#
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_USER=snipe
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=snipe
#---------Snipe-it------------#
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipeit
    depends_on: 
     - mysql
    restart: unless-stopped
    volumes:
      - /home/snipe_it:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snipeitrouter.rule=Host(`snipeit.gregoriogadea.site`)"
      - "traefik.http.routers.snipeitrouter.entrypoints=websecure"
      - "traefik.http.routers.snipeitrouter.tls.certresolver=snipeitrouter-letsencrypt"
    environment:
      - APP_URL=https://snipeit.gregoriogadea.site # <--- Your snipe-it domain here
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=test
      - PGID=1000
      - PUID=1000
#---------Traefik------------#
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # (optional) expose the dashboard !don't use in production!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/letsencrypt:/letsencrypt
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.snipeitrouter-letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.snipeitrouter-letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.snipeitrouter-letsencrypt.acme.email=<PUT YOUR E-MAIL HERE>"
      - "--certificatesresolvers.snipeitrouter-letsencrypt.acme.storage=/letsencrypt/acme.json" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.snipeit.gregoriogadea.site`)" # <--- Your domain for the dashboard here
      - "traefik.http.routers.api.service=api@internal"
      #- "traefik.http.routers.api.middlewares=auth"
      #- "traefik.http.middlewares.auth.basicauth.users=admin:test1234"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=snipeitrouter-letsencrypt"
    restart: unless-stopped